### PR TITLE
Removed check option from dotnet-format as that option disables savin…

### PR DESCRIPTION
**Pull request by TimGreen-io**
…g changed files

See https://github.com/dotnet/format#:~:text=dotnet%2Dformat%20is%20a%20code,of%20preferences%20will%20be%20used.

### CODE REVIEW

**Review by Emily-Steel — APPROVED** [review]
LGTM. Most of the formatting issues we see are around whitespacing/minor format issues that aren't worth correcting by hand so letting `dotnet-format` autofix whatever it can is beneficial

**Review by petemounce — APPROVED** [review]

**Comment by Emily-Steel** [comment]
@petemounce There doesn't seem to be an OWNERS file in this repo so it didn't mark this PR as approved. Could you manually merge it for us please? Would adding an OWNERS file allow us to pull the "merge" trigger next time once it has the approved label?

**Comment by petemounce** [comment]
@Christopher-Steel this doesn't have prow wired up all the way. @DoomGerbil and I will fix that Monday; apologies.

**Pull request merged**
